In [1]:
import io, os, sys, types
from IPython import get_ipython
from nbformat import read
from IPython.core.interactiveshell import InteractiveShell
import glob

In [2]:
def find_notebook(fullname, path=None):
    """find a notebook, given its fully qualified name and an optional path

    This turns "foo.bar" into "foo/bar.ipynb"
    and tries turning "Foo_Bar" into "Foo Bar" if Foo_Bar
    does not exist.
    """
    name = fullname.rsplit('.', 1)[-1]
    if not path:
        path = ['']
    for d in path:
        nb_path = os.path.join(d, name + ".ipynb")
        if os.path.isfile(nb_path):
            return nb_path
        # let import Notebook_Name find "Notebook Name.ipynb"
        nb_path = nb_path.replace("_", " ")
        if os.path.isfile(nb_path):
            return nb_path


class NotebookLoader(object):
    """Module Loader for Jupyter Notebooks"""
    def __init__(self, path=None):
        self.shell = InteractiveShell.instance()
        self.path = path
        
    def load_module(self, fullname):
        """import a notebook as a module"""
        path = find_notebook(fullname, self.path)

        print ("importing Jupyter notebook from %s" % path)

        # load the notebook object
        with io.open(path, 'r', encoding='utf-8') as f:
            nb = read(f, 4)


        # create the module and add it to sys.modules
        # if name in sys.modules:
        #    return sys.modules[name]
        mod = types.ModuleType(fullname)
        mod.__file__ = path
        mod.__loader__ = self
        mod.__dict__['get_ipython'] = get_ipython
        sys.modules[fullname] = mod

        # extra work to ensure that magics that would affect the user_ns
        # actually affect the notebook module's ns
        save_user_ns = self.shell.user_ns
        self.shell.user_ns = mod.__dict__

        try:
            for cell in nb.cells:
                if cell.cell_type == 'code':
                    # transform the input to executable Python
                    code = self.shell.input_transformer_manager.transform_cell(cell.source)
                    # run the code in themodule
                    exec(code, mod.__dict__)
        finally:
            self.shell.user_ns = save_user_ns
        return mod

class NotebookFinder(object):
    """Module finder that locates Jupyter Notebooks"""
    def __init__(self):
        self.loaders = {}

    def find_module(self, fullname, path=None):
        nb_path = find_notebook(fullname, path)
        if not nb_path:
            return

        key = path
        if path:
            # lists aren't hashable
            key = os.path.sep.join(path)

        if key not in self.loaders:
            self.loaders[key] = NotebookLoader(path)
        return self.loaders[key]

sys.meta_path.append(NotebookFinder())

In [10]:
scrapers = [state.split('.')[0] for state in glob.glob('*county.ipynb')]

In [11]:
scrapers

['CA by county',
 'WA by county',
 'NY by county',
 'MI by county',
 'VA by county',
 'MD by county']

In [15]:
import importlib

for scraper in scrapers:
    i = importlib.import_module(scrapers)
    try:
        i.run()
    except:
        print(f'Error scraping {scraper}.')
        traceback.print_exc()

importing Jupyter notebook from CA by county.ipynb

In [5]:
import MI_by_county as c

importing Jupyter notebook from MI by county.ipynb

In [6]:
c.fetch()

            county positive_cases  deaths
0           County          Cases  Deaths
1            Barry              1
2              Bay              1
3          Berrien              2
4          Calhoun              1
5       Charlevoix              1
6            Clare              1
7          Clinton              2
8     Detroit City            248       3
9            Eaton              2
10         Genesee              7
11          Ingham             11
12         Jackson              1
13            Kent             21
14        Leelanau              1
15      Livingston              6
16          Macomb            101
17         Midland              3
18          Monroe              3
19        Montcalm              1
20         Oakland            229       1
21          Otsego              1
22          Ottawa              2
23         Saginaw              1
24       St. Clair              7
25         Tuscola              1
26       Washtenaw             29
27           Wayne            101       1
28         Wexford              1
29    Out of State              1
30           Total            787       5